### PR TITLE
Fix busId comparions

### LINKED ISSUE #3: Issues with usbip-win on windows 10
Hi, i really like your project, but i came across some issues.

So my setup is - windows 10, i installed usbip-win version 0.3.5 from https://github.com/cezanne/usbip-win.
I try to run localy keyboard example on native windows 10.

When i tried to use your repo, i got problems when running keyboard example:
1. when calling  '''./usbip attach -r 127.0.0.1 -b 0'''
 example doesn't detect bus, because usbip-win sends bus id in format like "0\0fefefefefe..." - and you check for "0\0\0\0\0\0\0..."
 I've fixed it by checking if one bus sctring contains another.
2. than it doesnt work - and get stuck in loop, reporting wrong packet requests from client. I've found solution for that by manualy replacing:
0x02,                              // bcdUSB: USB 2.1
value with 
0x01,                              // bcdUSB

and 
self.ep0_in.max_packet_size as u8, // bMaxPacketSize0
with 
0x08,                 // bMaxPacketSize0

I found that values by trying mimic python/c baced repo, which works with usbip-win.

Now, i have one last problem, which i don't know how to fix.
When i run example - it runs, it creates new HID keyboard device, and even sends 1 as input... But, it doesn't just send one "1" per second - it's like spams it. (like 10-20 characters per second).

So, question is, where i can get compatible version of usbip-win client which works correctly with your example (and on win 10).
Or, what i should additionaly change to fix the issue of auto-repeated characters, on busy server (i've observed, that when server doesn't reply for like 250ms it starts to spam last character.
My goal is to have something like: 127x0x0x1 string outputed fast, and than - to do nothing for next ten seconds, than repeat.
And my ultimate goal is to have syncronous api which i can call something like PressKey("A"); ReleaseKey("A"); from thread with logic, imitating human input.

Trying to wrap my head around this issue for last few days with no luck...

I'm really new to rust and usbip/hid so any help or suggestions are appreciated.

### PR DESCRIPTION
**Pull request by 313ctric**
This partly fixes #3.
Changes the busId check to use a null-terminated string comparison.

### CODE REVIEW

**Comment by jiegec** [comment]
Maybe it is possible to use std::ffi::CString?

File: src/util.rs [hunk 1]
```diff
@@ -20,6 +20,18 @@ pub fn verify_descriptor(desc: &[u8]) {
...
+pub fn str_eq(a: &[u8], b: &[u8]) -> bool {
+    for (x, y) in a.iter().chain([0].iter()).zip(b.iter().chain([0].iter())) {
+        if x != y {
+            return false;
+        }
+        if *x == 0 {
+            return true;
+        }
+    }
+    unreachable!()
```
Comment (jiegec) [inline src/util.rs:32]: It is a bad practice to use anything that can panic in a library.

**Comment by h7x4** [comment]
I had a look at the usbip-win source code.

https://github.com/cezanne/usbip-win/blob/95ccf0a8863b0eeb75dd383cb5ac863c825286f2/userspace/src/usbip/usbip_attach.c#L166-L170

`strncmp` seems to only compare until the first `\0`, meaning that if we return `{busid}\0\0\0...`, it shouldn't be a problem.

This is consistent with [the linux kernel docs](https://docs.kernel.org/usb/usbip_protocol.html#protocol-version), which says

> Bus ID of the exported device, string closed with zero byte, e.g. "3-2". The unused bytes shall be filled with zero bytes.

From this, I'm reading that the remaining `0x00` or `0xFE` bytes are not supposed to be regarded as a part of `busId`.

I think rewriting the comparison logic for strings would just be addressing the symptoms. The real bug is that we're storing bytes after the first null byte in the string, as if it was part of the `busId`. I think it would be better to strip the string on creation.

**Comment by 313ctric** [comment]
Good point about just stripping the strings. This should be good now.

(may need a small chage to deal with a changed variable name, but I don't know enough about git to do merge conflicts or anything like that)
